---
title: ""
output: 
  html_document: 
    toc: yes
    toc_float:
      toc_collapsed: no
    theme: cosmo
---
  
# easyPlot

**Effortless Data Visualization with ggplot2**

`easyPlot` is a Shiny app crafted for ggplot2, simplifying the creation of scatterplots, histograms, boxplots, and bar charts.



----------------------------------------------------

# Key features

- **Seamless Data Upload:** Easily import data in various formats (csv, xlsx, txt) for a smooth start to your visualization journey.

- **Swift Visualization:** Swiftly explore patterns and relationships within your dataset, providing quick insights.

- **Multivariate Visualizations:** Visualize multiple variables simultaneously, enhancing the depth of data exploration in a single graph.

- **Flexible Styling:** Customize the appearance of your graphs by adjusting colors, themes, and other visual elements to suit your preferences.

- **Interactive Scatterplot:** Identify outliers, calculate summary statistics for marked points, and efficiently zoom into specific areas for enhanced data exploration.

- **Reproducibility:** Benefit from automatic generation of R code corresponding to your plots, ensuring easy reproduction and integration into your scripts and reports.


----------------------------------------------------

# Privacy policy

We want to assure our users that no data is stored or processed on our server after it is uploaded to the easyPlot app. Your data remains private and secure throughout the usage of the application. We prioritize the confidentiality and privacy of your information.

**Data Handling:**

1. **No Storage:** The `easyPlot` app does not store any data uploaded by users on our server. Once you upload your data, it is processed in real-time for visualization purposes only.

2. **Real-time Processing:** Data uploaded to the app is processed in real-time exclusively for generating plots and visualizations within the application interface.

3. **No Tracking:** We do not track or store any personal information related to your data. Your usage of the app is anonymous, and we do not collect any identifiable information.

**User Responsibility:**

1. **Secure Data Transmission:** While we take measures to ensure the security of your data within the app, please ensure that you do not upload sensitive or confidential information.

2. **Session-based Processing:** The app processes your data on a session-by-session basis. Once you close or leave the app, there is no retention of the data from your previous sessions.

3. **External Links:** The app may provide links to external sources for additional information or resources. Please be aware that our privacy policy applies only to data processed within the `easyPlot` app.

By using the `easyPlot` app, you acknowledge and agree to the terms outlined in this privacy disclaimer. If you have any concerns or questions regarding privacy, please contact us. Your privacy and trust are of utmost importance to us.

----------------------------------------------------

# Connect

- For feedback, feature requests, and bug reports, please visit my [GitHub repository](https://github.com/majkamichal/easyPlot).
  
- Contact me at [michalmajka@hotmail.com](mailto:michalmajka@hotmail.com).
  
- Follow me on [Twitter](https://twitter.com/majkamichal) and [LinkedIn](https://www.linkedin.com/in/michal-majka/) for updates.
    
- If you find easyPlot valuable and would like to support my work, consider [buy me a coffee](https://www.buymeacoffee.com/michalmajka).

----------------------------------------------------
    
**Thank you for using easyPlot!**
      
----------------------------------------------------
